Variable and type
Asady1113/MyCloset2 pull request #3
Opened 2023-07-16 08:38 UTC by Asady1113

【CodeCoaching】変数と型の修正
・コーディング規約を参考に、変数と型に修正を加えてみました
・対象はModelとViewControllerになります
・単純な型推論やvar,letなどはある程度修正しましたが、そもそも型推論や糖衣構文で書けると気づいていない箇所もあると思われます

2023-07-17 15:03 UTC, YR-MO requested changes

2023-07-17 15:03 UTC, YR-MO commented on MyCloset2/ViewController/ResultViewController.swift
> +        let image = UIImage(data: data!)
今回の内容ではないが、「!」を使って強制的にnullableをnonnullにするのは、
コードの安全性を損ねるため、
```
if let data = data {
    let image = UIImage(data: data)
}
```
のように、確実にnonnullにしましょう🙆‍♂

2023-07-17 15:15 UTC, YR-MO commented
ブランチ名ですが、
試しに「feature/XXX」や「feat/XXX」のような、実務を意識したブランチ名にするのもいいと思います🙆‍♂

2023-07-18 14:02 UTC, YR-MO requested changes

2023-07-18 14:02 UTC, YR-MO commented on MyCloset2/ViewController/SearchViewController.swift
>      //配列の中身を判定する
カーソルを関数名の行に置いて、
XCodeで「`option + command + /`」を押して、
コメントの自動生成をお試しに使用してみてね😃

2023-07-19 05:15 UTC, Asady1113 commented on MyCloset2/ViewController/AddViewController.swift
> +        let placeholderImage = "clothes-placeholder-icon@2x.png"
レビューとは関係ありませんでしたが、冗長に見えたので修正しました

2023-07-19 16:38 UTC, YR-MO requested changes

2023-07-19 16:38 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +    func isOverTwoYearsSinceLastWorn(clothes: Clothes) -> Bool {
具体的な数字（英語でも）が直接関数名や変数名などになるのはやはり好ましくないですね。

原因としては、プロジェクトの将来性を考慮し、
今は2年だけど、将来は仕様変更で1年や3年、
あるいはこの時間がユーザー設定可能になる場合があります。

ですので、この2年は一体何を指すのか、
その意味合いで命名してみてね😃

2023-07-21 15:44 UTC, YR-MO requested changes

2023-07-21 15:44 UTC, YR-MO commented on MyCloset2/ViewController/SearchViewController.swift
> -    var currentConditions: String = "Category"
Conditionsに関して、Stringではなく、
enumを試しに使ってみてね。

原因ですと、「状況」「状態」のような使い方ですと、
String型は意図せぬ値になる可能性があるので、
できれば値を範囲を制限したいです。
このような状況は、enumがおすすめです。🙆‍♂

2023-07-21 15:44 UTC, YR-MO commented on MyCloset2/ViewController/SearchViewController.swift
> +    func getConditions(conditions: String) -> [String] {
getConditionsは、「この状態を取得する」という意味合いになっていて、
実際関数の中身を見ますと、
`Conditionによる、違うCandidateの配列を取得する`ということみたいですね、
関数名と実際の機能が一致してないように見えます。

「XXを使って、YYを取得する」という関数は、
「getYYByXX」のが主流です。
ですので、この関数は`getCandidatesByCondition`のほうがいいかもしれません。🙆‍♂

2023-07-23 07:24 UTC, Asady1113 commented on MyCloset2/ViewController/SearchViewController.swift
> +    enum Conditions {
自分なりに調べて使用してみましたが、使い方が適切なのかはあまり自信はありません

2023-07-23 12:56 UTC, YR-MO commented on MyCloset2/ViewController/SearchViewController.swift
> +    enum Conditions {
@Asady1113 今の段階では、この使用は問題ないです🙆‍♂
enumの基本を掴めばOKです。

もちろんenumは他の機能はありますが、
それは基本をちゃんと把握してから少しずつ勉強しましょう👍

2023-07-23 13:00 UTC, YR-MO approved these changes
まだ改善点はありますが、
しかしこのプルリクの変更も多いので、一旦ここで承認致します🙆‍♂

このプルリクをマージして大丈夫です。
マージしたあと、試しに、mainブランチの変更を各作業ブランチに取り込んでみてね👍
もしかしたら競合が発生しますので、その時は試しに解決してみてください🙏
焦らずに、やってね😃

2023-07-24 04:38 UTC, merged