Feature/error handling
Asady1113/MyCloset2 pull request #5
Opened 2023-07-23 09:19 UTC by Asady1113

【CodeCoaching】エラーハンドリングの修正
・コーディング規約を参考に、エラーハンドリングに修正を加えてみました
・対象はModel/LoadFunctionとResultViewControllerになります（他のファイルはまだ変更していません）
・できる限り「！」を使わないよう心がけたつもりです。まだ十分に安全ではない箇所もあると思うので、ご指摘お願いいたします。

2023-07-23 13:11 UTC, YR-MO requested changes

2023-07-23 13:11 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +        if let result = realm?.objects(Clothes.self).filter("category== %@", category) {
realmがnilの場合、実は次の処理をやらなくで大丈夫ですので、
複合条件のifにしても大丈夫と思います
```
if 
    let realm = try? Realm(), 
    let result = realm.objects(Clothes.self).filter("category== %@", category) {...}
```
のような。🙆‍♂

2023-07-23 13:11 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +            if let result = realm?.objects(Clothes.self).filter("id== %@", clothesId) {
中身のifはelse-ifやelseがない限り、
2重ifではなく、
一つのifに、「`,`」で複合条件にしましょう👍
※他の所も横展開してみてね😃

swiftでは「`,`」になるが、
多くの言語では、andだと「`&&`」、orだと「`||`」になります。
「理論演算子」の関連の知識を身に付けるほうがいいでしょう🙆‍♂

原因はすごく理論的な知識になるため、今回は割愛しますが、
条件（if文など）やループ（for文、while文など）を書く時、
「`{}`」の階層が浅いほど、パフォーマンスが良くなりますので、
まずはif文だけでも、工夫しましょう🙆‍♂

2023-07-29 16:41 UTC, YR-MO approved these changes

2023-07-29 16:41 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +                    putOnCount = putOnCount - 1
```
putOnCount -= 1
```
のような簡約な記述を使用してみてね😃

2023-07-29 16:41 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +            if dateSubtraction > 0 {
次の処理では、dateSubtractionが使用されてなければ、

`Int(notificateDate.timeIntervalSince(date)) > 0` のように、1つ目のifに合併し、
`{}` の階層を減らせると思います🙆‍♂

2023-07-29 16:41 UTC, YR-MO commented on MyCloset2/ViewController/ResultViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") as? ClothesTableViewCell
次の処理で、わざわざ`?`を書くたくない場合は、
```
guard let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") as? ClothesTableViewCell else {
    fatalError()
}
```
のように書くのもありと思います。

※ fatalErrorはアプリクラッシュを起こす関数になるが、
そもそもcell取得できないのは**存在してはならない**ことですので、
ここでfatalErrorを使用するのは合理的になります。
多くのプロジェクトは合理的なfatalErrorを使用しています🙆‍♂

2023-07-29 16:41 UTC, YR-MO commented on MyCloset2/ViewController/ResultViewController.swift
> +        let realm = try? Realm()
realm を他の処理では使わない場合、`let realm = try? Realm()` をifに入れてもOKです。
if内に使い捨ての変数を定義するのも、パフォーマンス向上に少しだけですが、役は立つと思います🙆‍♂

2023-07-29 16:43 UTC, YR-MO requested changes
この4ファイル以外のファイルも、
「if」を全プロジェクトで検索してみて、
全体的の横展開もしてみてね😊

2023-07-30 08:48 UTC, Asady1113 commented on MyCloset2/Model/LoadFunctions.swift
> +            if dateSubtraction > 0 {
この場合は、timeIntervalSinceが差分を出していることは誰が見てもわかるので、変数に入れずに使っても良いということでしょうか。（意図をわかりやすくするために変数に入れた方が良いかと思って変数にしてしまいました、、）

2023-07-30 08:59 UTC, Asady1113 commented on MyCloset2/ViewController/ResultViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") as? ClothesTableViewCell
これと、強制アンラップ(!)を使用する場合とでは何が異なりますか？（強制アンラップもnilの場合はアプリクラッシュすると認識しています）

機能的には同じですが、
```
guard let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") as? ClothesTableViewCell else {
    fatalError()
}
```
の方が読み手にとってcellがnilになることは想定しないということが伝わりやすいということでしょうか。

2023-07-30 12:28 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +            if dateSubtraction > 0 {
ifなどの`条件文でしか`使用しないものは、変数に入れなくで大丈夫です。
意図などは`コメント`での補足があれば大丈夫です🙆‍♂

変数にしないのはいろんな意図がありまして、
変数宣言の減少によるパフォーマンスアップ、
後続の処理で使用してないのに定義された変数が、読み手にとっては「後続で使用されるのでは？」って混乱になってしまう、など...

確かにプログラミングを始まったばっかりの頃は、変数に入れてみるのは理解できる😃、
debugのしやすいし、良いところもある。
しかし、時間を経つと、必要でないコードをできるだけ減らしたくなります。
コードは単に「読みやすさ」だけでなく、「簡潔さ」も大事ですので🙆‍♂
いまから「簡潔さ」も意識するのが大事だと思います👍

2023-07-30 12:34 UTC, YR-MO commented on MyCloset2/ViewController/ResultViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "Cell") as? ClothesTableViewCell
@Asady1113 

この処理だけの話だと、本質は「!」と変わりがないが、
しかし、「!」の使用は「意図せぬクラッシュ」に対して、
ここは「意図したクラッシュ」になります。

2023-08-05 12:09 UTC, YR-MO requested changes

2023-08-05 12:09 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +            if Int(notificateDate.timeIntervalSince(date)) > 0 {
1つ目のifに合併してみてね

```
if let notificateDate = calendar.date(byAdding: .day, value: MaxDurationOfNotWorn, to: date),
    Int(notificateDate.timeIntervalSince(date)) > 0 { //通知時間が未来であること（差分が0より大きい）が条件（クラッシュ防止）

 // ...
}

2023-08-05 12:09 UTC, YR-MO commented on MyCloset2/ViewController/ResultViewController.swift
> +        if loadFunction.isOverMaxDurationSinceLastWorn(clothes: clothesArray[indexPath.row]) == true {
今の段階は「== true」を書いて構わないが、
将来的には、`nonnull`の結果の対してのtrue判定は、「== true」を省略して大丈夫です🙆‍♂
※`nullable`の場合は「== true」を書かなければいけない。

2023-08-05 12:09 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +                     if let error = error {
`if let error { ... } `に略できます🙆‍♂

2023-08-05 12:09 UTC, YR-MO commented on MyCloset2/ViewController/DetailViewController.swift
> +        if let realm = try? Realm(), let id = selectedClothes.id, let category = selectedClothes.category, let name = nameTextField.text, let buyDateString = buyDateTextField.text, let price = priceT
ifは改行できるので、複数条件の場合、改行で可読性をアップしましょう🙆‍♂

```
if let realm = try? Realm(), 
    let id = selectedClothes.id, 
    let category = selectedClothes.category, 
    let name = nameTextField.text, 
    let buyDateString = buyDateTextField.text, 
    let price = priceTextField.text, 
    let comment = commentTextView.text, 
    let color = colorTextField.text, 
    let imageData = imageData, 
    let notificationId = selectedClothes.notificationId {
    // ...
}
```

2023-08-06 15:20 UTC, Asady1113 commented on MyCloset2/Model/LoadFunctions.swift
> +                     if let error = error {
こちらは今まで使用してきたオプショナルバインディング全てに導入することは可能でしょうか？
(error以外の際にも使用可能でしょうか）

[参照記事](https://github.com/stzn/SwiftPodcast/blob/main/episodes/Swift%20%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%83%90%E3%82%A4%E3%83%B3%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E6%99%82%E3%81%AE%E5%A4%89%E6%95%B0%E3%81%AE%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97%E3%82%92%E9%81%BF%E3%81%91%E3%82%8Bif%20let%E3%81%AA%E3%81%A9%E3%81%AE%E7%9C%81%E7%95%A5%E6%A7%8B%E6%96%87.md#swift-%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%8A%E3%83%AB%E3%83%90%E3%82%A4%E3%83%B3%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E6%99%82%E3%81%AE%E5%A4%89%E6%95%B0%E3%81%AE%E7%B9%B0%E3%82%8A%E8%BF%94%E3%81%97%E3%82%92%E9%81%BF%E3%81%91%E3%82%8Bif-let%E3%81%AA%E3%81%A9%E3%81%AE%E7%9C%81%E7%95%A5%E6%A7%8B%E6%96%87)

2023-08-07 06:47 UTC, YR-MO commented on MyCloset2/Model/LoadFunctions.swift
> +                     if let error = error {
@Asady1113 はい、全部導入可能です🙆‍♂️

2023-08-13 03:51 UTC, YR-MO commented on MyCloset2/ViewController/OthersViewController.swift
> +            let detailViewController = segue.destination as? DetailViewController
この文は、下のifの中に移動するほうがいいでしょう。

原因としては、
今は、ifの条件がfalseでも、この文は実行されるます、
ある意味無効な実行になります、
些細なことですが、できればすべてのコードも有効なコードにしましょう👍

2023-08-14 11:09 UTC, YR-MO approved these changes

2023-08-19 05:00 UTC, merged